project_name: Coinmaxify

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: darwin-amd64
    main: ./main.go
    binary: Coinmaxify
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags:
      -s -w -X 'github.com/Coinmaxify/Coinmaxify/versioning.Version=v{{ .Version }}'

  - id: darwin-arm64
    main: ./main.go
    binary: Coinmaxify
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      -s -w -X 'github.com/Coinmaxify/Coinmaxify/versioning.Version=v{{ .Version }}'

  - id: linux-amd64
    main: ./main.go
    binary: Coinmaxify
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      -s -w -linkmode external -extldflags "-static" -X 'github.com/Coinmaxify/Coinmaxify/versioning.Version=v{{ .Version }}'

  - id: linux-arm64
    main: ./main.go
    binary: Coinmaxify
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      -s -w -linkmode external -extldflags "-static" -X 'github.com/Coinmaxify/Coinmaxify/versioning.Version=v{{ .Version }}'

archives:
  -
    files:
    - LICENSE
    - README.md

#nfpms:
#  - vendor: 0xCoinmaxify
#    homepage: https://Coinmaxify.technology
#    maintainer: Coinmaxify Team <edge@Coinmaxify.technology>
#    description:  A Framework for Building Ethereum-compatible Blockchain Networks
#    license: GPLv3 LGPLv3
#
#    formats:
#      - apk
#      - deb
#      - rpm
#
#    contents:
#      - src: Coinmaxify.service
#        dst: /lib/systemd/system/Coinmaxify.service
#        type: config
#
#    overrides:
#      rpm:
#        replacements:
#          amd64: x86_64

snapshot:
  name_template: "{{ .Tag }}.next"

dockers:
  - image_templates:
      - 0xCoinmaxify/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: amd64
    ids:
      - linux-amd64
    build_flag_templates:
      - --platform=linux/amd64
    skip_push: false

  - image_templates:
      - 0xCoinmaxify/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: arm64
    ids:
      - linux-arm64
    build_flag_templates:
      - --platform=linux/arm64
    skip_push: false

docker_manifests:
  - name_template: 0xCoinmaxify/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - 0xCoinmaxify/{{ .ProjectName }}:{{ .Version }}-amd64
      - 0xCoinmaxify/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: false

  - name_template: 0xCoinmaxify/{{ .ProjectName }}:latest
    image_templates:
      - 0xCoinmaxify/{{ .ProjectName }}:{{ .Version }}-amd64
      - 0xCoinmaxify/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: false
